In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("/content/creditcard.csv")

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.shape

(284807, 31)

In [5]:
#Check null values
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
#Check data types
df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [7]:
df["Class"].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [8]:
X=df[["Time","Amount"]]
Y=df["Class"]

In [9]:
Y.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [11]:
#Apply StandardScaler on X_train input and X_test input
from sklearn.preprocessing import StandardScaler
#Create object of StandardScaler class
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [12]:
X_train

array([[ 0.72077679, -0.29504251],
       [ 0.10526749, -0.31649663],
       [ 1.36935421, -0.3445428 ],
       ...,
       [-0.83845867, -0.32216979],
       [ 1.42856088,  0.02628993],
       [-0.34389022, -0.12153178]])

In [13]:
X_test

array([[ 0.52664377, -0.34530189],
       [-0.34886097, -0.3445428 ],
       [-0.26372636, -0.34889755],
       ...,
       [-1.28304582, -0.29168655],
       [ 0.78887184, -0.23263777],
       [-1.28671069, -0.0569297 ]])

In [14]:
Y_train.value_counts()

0    199007
1       357
Name: Class, dtype: int64

In [15]:
#Value count of 0 is more than double of 1
#Apply random over sampler
from imblearn.over_sampling import RandomOverSampler
ros=RandomOverSampler(random_state=1)

In [16]:
X_train1,Y_train1=ros.fit_resample(X_train,Y_train)

In [17]:
Y_train1.value_counts()

0    199007
1    199007
Name: Class, dtype: int64

In [18]:
X_train1.shape,Y_train1.shape

((398014, 2), (398014,))

In [20]:
Y_test.value_counts()

0    85308
1      135
Name: Class, dtype: int64

In [21]:
#Value count of 0 is more than double of 1
#Here also apply random over sampler
X_test1,Y_test1=ros.fit_resample(X_test,Y_test)

In [22]:
X_test1.shape,Y_test1.shape

((170616, 2), (170616,))

In [23]:
Y_test1.value_counts()

0    85308
1    85308
Name: Class, dtype: int64

In [24]:
#Create model
def create_model(model):
  model.fit(X_train1,Y_train1)
  Y_pred=model.predict(X_test1)
  print(confusion_matrix(Y_test1,Y_pred))
  print(classification_report(Y_test1,Y_pred))
  return model

In [25]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [26]:
#Now apply LogisticRegression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [27]:
#Call user defined function and passing the parameter lr
lr=create_model(lr)

[[43584 41724]
 [37241 48067]]
              precision    recall  f1-score   support

           0       0.54      0.51      0.52     85308
           1       0.54      0.56      0.55     85308

    accuracy                           0.54    170616
   macro avg       0.54      0.54      0.54    170616
weighted avg       0.54      0.54      0.54    170616



In [ ]:
 #Using LogisticRegression , Recall=56% and Accuracy=54%

In [28]:
#Now apply DecisionTreeClassifier by default gini index
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=1)

In [29]:
dt=create_model(dt)

[[85191   117]
 [75277 10031]]
              precision    recall  f1-score   support

           0       0.53      1.00      0.69     85308
           1       0.99      0.12      0.21     85308

    accuracy                           0.56    170616
   macro avg       0.76      0.56      0.45    170616
weighted avg       0.76      0.56      0.45    170616



In [ ]:
#Using DecisionTreeClassifier gini index, Recall=12% and Accuracy=56%

In [30]:
dict={"Input Column":X.columns,"IG":dt.feature_importances_}
df1=pd.DataFrame(dict)
df1
df1.sort_values("IG",ascending=False)

Input Column        IG
0         Time  0.501847
1       Amount  0.498153

In [31]:
#Now apply DecisionTreeClassifier using entropy
dt1=DecisionTreeClassifier(random_state=1,criterion="entropy")
print("Confusion Matrix and Classification Report")
dt1=create_model(dt1)

Confusion Matrix and Classification Report
[[85178   130]
 [75277 10031]]
              precision    recall  f1-score   support

           0       0.53      1.00      0.69     85308
           1       0.99      0.12      0.21     85308

    accuracy                           0.56    170616
   macro avg       0.76      0.56      0.45    170616
weighted avg       0.76      0.56      0.45    170616



In [ ]:
#Using DecisionTreeClassifier entropy, Recall=12% and Accuracy=56%

In [32]:
#Now apply RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

In [34]:
'''for i in range(10,101):
  rfc=RandomForestClassifier(random_state=1,n_estimators=i)
  print("No.of Tree: ",i)
  rfc=create_model(rfc)'''

'for i in range(10,101):\n  rfc=RandomForestClassifier(random_state=1,n_estimators=i)\n  print("No.of Tree: ",i)\n  rfc=create_model(rfc)'

In [45]:
rfc=RandomForestClassifier(random_state=1,n_estimators=41)
rfc=create_model(rfc)

[[85247    61]
 [74637 10671]]
              precision    recall  f1-score   support

           0       0.53      1.00      0.70     85308
           1       0.99      0.13      0.22     85308

    accuracy                           0.56    170616
   macro avg       0.76      0.56      0.46    170616
weighted avg       0.76      0.56      0.46    170616



In [ ]:
#Using RandomForestClassifier , Recall=13% and Accuracy=56%

In [36]:
#Now apply adaboost classifier
from sklearn.ensemble import AdaBoostClassifier

In [38]:
'''for i in range(1,17):
  ada=AdaBoostClassifier(random_state=1,n_estimators=i)
  print("No.of  decision stump means no.of input : ",i)
  ada=create_model(ada)'''

'for i in range(1,17):\n  ada=AdaBoostClassifier(random_state=1,n_estimators=i)\n  print("No.of  decision stump means no.of input : ",i)\n  ada=create_model(ada)'

In [46]:
ada=AdaBoostClassifier(random_state=1,n_estimators=13)
ada=create_model(ada)
ada.feature_importances_

[[56785 28523]
 [26680 58628]]
              precision    recall  f1-score   support

           0       0.68      0.67      0.67     85308
           1       0.67      0.69      0.68     85308

    accuracy                           0.68    170616
   macro avg       0.68      0.68      0.68    170616
weighted avg       0.68      0.68      0.68    170616



array([0.61538462, 0.38461538])

In [ ]:
#Using AdaBoostClassifier , Recall=69% and Accuracy=68%

In [40]:
#Now apply gradient boosting technique
from sklearn.ensemble import GradientBoostingClassifier

In [43]:
'''for i in range(10,101):
  gbc=GradientBoostingClassifier(random_state=1,n_estimators=i)
  print("No.of decision tree:",i)
  gbc=create_model(gbc)'''

'for i in range(10,101):\n  gbc=GradientBoostingClassifier(random_state=1,n_estimators=i)\n  print("No.of decision tree:",i)\n  gbc=create_model(gbc)'

In [47]:
gbc=GradientBoostingClassifier(random_state=1,n_estimators=88)
gbc=create_model(gbc)

[[71623 13685]
 [32829 52479]]
              precision    recall  f1-score   support

           0       0.69      0.84      0.75     85308
           1       0.79      0.62      0.69     85308

    accuracy                           0.73    170616
   macro avg       0.74      0.73      0.72    170616
weighted avg       0.74      0.73      0.72    170616



In [ ]:
#Using GradientBoostingClassifier, Recall=62% and Accuracy=73%

In [48]:
#Now apply xgb classifier
from xgboost import XGBClassifier

In [50]:
'''for i in range(10,101):
  xgb=XGBClassifier(random_state=1,n_estimators=i,reg_alpha=1)
  print("No.of estimators means tree:",i)
  xgb=create_model(xgb)'''

'for i in range(10,101):\n  xgb=XGBClassifier(random_state=1,n_estimators=i,reg_alpha=1)\n  print("No.of estimators means tree:",i)\n  xgb=create_model(xgb)'

In [51]:
xgb=XGBClassifier(random_state=1,n_estimators=10,reg_alpha=1)
xgb=create_model(xgb)

[[74092 11216]
 [38542 46766]]
              precision    recall  f1-score   support

           0       0.66      0.87      0.75     85308
           1       0.81      0.55      0.65     85308

    accuracy                           0.71    170616
   macro avg       0.73      0.71      0.70    170616
weighted avg       0.73      0.71      0.70    170616



In [ ]:
#Using XGBClassifier , Recall=55% and Accuracy=71%

In [52]:
#Using SVC technique
from sklearn.svm import LinearSVC

In [53]:
svc=LinearSVC()

In [54]:
svc=create_model(svc)

[[43574 41734]
 [37241 48067]]
              precision    recall  f1-score   support

           0       0.54      0.51      0.52     85308
           1       0.54      0.56      0.55     85308

    accuracy                           0.54    170616
   macro avg       0.54      0.54      0.54    170616
weighted avg       0.54      0.54      0.54    170616



In [57]:
#After adding some error
svc1=LinearSVC(random_state=1,C=0.9)
svc1=create_model(svc1)

[[43536 41772]
 [37241 48067]]
              precision    recall  f1-score   support

           0       0.54      0.51      0.52     85308
           1       0.54      0.56      0.55     85308

    accuracy                           0.54    170616
   macro avg       0.54      0.54      0.54    170616
weighted avg       0.54      0.54      0.54    170616



In [ ]:
#Using SVM class , Recall=56% and Accuracy=54%

In [ ]:
# Using LogisticRegression :
# Recall=56% and Accuracy=54%

# Using DecisionTreeClassifier gini index :
# Recall=12% and Accuracy=56%

# Using DecisionTreeClassifier entropy :
# Recall=12% and Accuracy=56%

# Using RandomForestClassifier :
# Recall=13% and Accuracy=56%

# Using AdaBoostClassifier :
# Recall=69% and Accuracy=68%

# Using GradientBoostingClassifier :
# Recall=62% and Accuracy=73%

# Using XGBClassifier :
# Recall=55% and Accuracy=71%

# Using SVM class :
# Recall=56% and Accuracy=54%

# The best algorithm for dataset creditcard.csv is AdaBoostClassifier
# Recall=69% and Accuracy=68%
